/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oskosh-truck.gltf 
Author: thientrung2004pr (https://sketchfab.com/U.SSCIFI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battlefield-6-oshkosh-fmtv-m1083-a8a91f91ef7a468faa7080f912c83ded
Title: Battlefield 6 - Oshkosh FMTV M1083
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

useGLTF.preload('/models/truck/oskosh-truck.gltf')

//
export default function OshkoshTruck(props) {

  const { nodes, materials } = useGLTF('/models/truck/oskosh-truck.gltf')
  // const { nodes, materials } = useGLTF('/models/truck/TruckOshkosh.glb')

  // console.log('OshkoshTruck materials:', materials)

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Bars1Mtl.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Bars1Mtl.001']} />

        <mesh geometry={nodes.Object_4.geometry} material={materials['Cab14Mtl.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Cab21Mtl.001']} />

        <mesh geometry={nodes.Object_10.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Decals21Mtl.001']} />

        <mesh geometry={nodes.Object_17.geometry} material={materials['FrTurningLights1Mtl.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Glass1Mtl.001']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['GlassLights1Mtl.001']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['HazardLights2Mtl.001']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Headlights1Mtl.001']} />

        <mesh geometry={nodes.Object_22.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['InteriorFrame4Mtl.001']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['RlTurningLight1Mtl.001']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Tailgate1Mtl.001']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Tailgate1Mtl.001']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Tailgate1Mtl.001']} />

        <mesh geometry={nodes.Object_34.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Wheel1Mtl.001']} />
      </group>
    </group>
  )
}  // OshkoshTruck

//*
export function TruckParts(props) {

  // const { nodes, materials } = useGLTF('/models/truck/oskosh-truck.gltf')
  const { scene } = useGLTF('/models/truck/Untitled.glb')

  // console.log(scene.children)
  // console.log(scene.children[0].children[0].children)

  {/** chassis without wheels */ }
  const geometry = scene.children[0].children[0].children[0].geometry
  const material = scene.children[0].children[0].children[0].material

  // material.color.set({isColor: true, r: 64, g: 32, b: 16} )
  material.color.set({ isColor: true, r: 230, g: 220, b: 220 })
  material.metalness = 0.85
  material.roughness = 0.35

  // other parts from the imported scene 
  //1 wheel's rotors:
  const geometry01 = scene.children[0].children[0].children[1].geometry
  const material01 = scene.children[0].children[0].children[1].material

  //2 chassis without wheels
  const geometry02 = scene.children[0].children[0].children[2].geometry
  const material02 = scene.children[0].children[0].children[2].material

  //3  Aufbauten oberes chassis 
  const geometry03 = scene.children[0].children[0].children[3].geometry
  const material03 = scene.children[0].children[0].children[3].material

  //4 Leiterrahmen mit Tanks
  const geometry04 = scene.children[0].children[0].children[4].geometry
  const material04 = scene.children[0].children[0].children[4].material

  //5 Leiterrahmen mit Tanks
  const geometry05 = scene.children[0].children[0].children[5].geometry
  const material05 = scene.children[0].children[0].children[5].material

  //6 Decals, Aufkleber, Beschriftungen
  const geometry06 = scene.children[0].children[0].children[6].geometry
  const material06 = scene.children[0].children[0].children[6].material

  //7 Decals, Aufkleber, Beschriftungen
  const geometry07 = scene.children[0].children[0].children[7].geometry
  const material07 = scene.children[0].children[0].children[7].material

  //8 tinted glass objects (dark), windows, lights
  const geometry08 = scene.children[0].children[0].children[8].geometry
  const material08 = scene.children[0].children[0].children[8].material

  //9 tinted glass objects (light), windows, lights
  const geometry09 = scene.children[0].children[0].children[9].geometry
  const material09 = scene.children[0].children[0].children[9].material

  //10 frame for the canvas / Abdeckung
  const geometry10 = scene.children[0].children[0].children[10].geometry
  const material10 = scene.children[0].children[0].children[10].material

  //11 Blinker und Leuchten
  const geometry11 = scene.children[0].children[0].children[11].geometry
  const material11 = scene.children[0].children[0].children[11].material

  //12 Blinker und Leuchten, rund
  const geometry12 = scene.children[0].children[0].children[12].geometry
  const material12 = scene.children[0].children[0].children[12].material

  //13 Rahmen der Kabine
  const geometry13 = scene.children[0].children[0].children[13].geometry
  const material13 = scene.children[0].children[0].children[13].material

  //14 Türen der Kabine
  const geometry14 = scene.children[0].children[0].children[14].geometry
  const material14 = scene.children[0].children[0].children[14].material

  //15 zweite Kabine
  const geometry15 = scene.children[0].children[0].children[15].geometry
  const material15 = scene.children[0].children[0].children[15].material

  // 
  return (
    <>
      <primitive object={scene} {...props} />
      {/* <primitive object={scene} position={[5, -0.25, 5]} scale={0.20} /> */}

      {/* <mesh geometry={geometry} material={material} {...props} scale={0.50} castShadow receiveShadow /> */}
      {/* <mesh geometry={geometry01} material={material01} {...props} scale={0.50} castShadow receiveShadow /> */}
      {/* <mesh geometry={geometry02} material={material02} {...props} scale={0.50} castShadow receiveShadow /> */}
      {/* <mesh geometry={geometry03} material={material03} {...props} scale={0.50} castShadow receiveShadow /> */}

      {/* <mesh geometry={geometry15} material={material15} {...props} scale={0.50} castShadow receiveShadow /> */}

    </>
  )
}  // TruckParts()
