/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oskosh-truck.gltf 
Author: thientrung2004pr (https://sketchfab.com/U.SSCIFI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battlefield-6-oshkosh-fmtv-m1083-a8a91f91ef7a468faa7080f912c83ded
Title: Battlefield 6 - Oshkosh FMTV M1083
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

useGLTF.preload('/models/truck/oskosh-truck.gltf')

//
export default function OshkoshTruck(props) {

  const { nodes, materials } = useGLTF('/models/truck/oskosh-truck.gltf')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Bars1Mtl.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Bars1Mtl.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Cab14Mtl.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Cab21Mtl.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Chasis21Mtl.001']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Decals21Mtl.001']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['FrTurningLights1Mtl.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Glass1Mtl.001']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['GlassLights1Mtl.001']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['HazardLights2Mtl.001']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Headlights1Mtl.001']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['InteriorFrame1Mtl.001']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['InteriorFrame4Mtl.001']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['RlTurningLight1Mtl.001']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['SteeringWheel1Mtl.001']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Tailgate1Mtl.001']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Tailgate1Mtl.001']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Tailgate1Mtl.001']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Wheel1Mtl.001']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Wheel1Mtl.001']} />
      </group>
    </group>
  )
}  // OshkoshTruck
